
name: docs-thenwewin-app
on: 
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:

  deploy-over-ssh:
    name: SSH and deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/{{ secrets.PATH }}/tww-app/
          git pull origin master
          cd docs/
          service docs restart 
