name: frontend-thenwewin-app
on: 
  push:
    branches:
      - master
    paths:
      - 'front/**'
  workflow_dispatch:
jobs:

  deploy-over-ssh:
    name: SSH and deploy
    runs-on: ubuntu-latest
    environment:
      name: link
      url: https://app.thenwewin.org
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ajay/tww-app/
          git pull origin master
          cd front/
          yarn install
          sudo service front restart 
