
name: backend-thenwewin-app
on: 
  push:
    branches:
      - master
    paths:
      - 'platform/**'
  workflow_dispatch:
jobs:

  deploy-over-ssh:
    name: SSH and deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      env:
        url: api-app.thenwewin.org
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/{{ secrets.PATH }}/tww-app/
          git pull origin master
          cd platform/
          yarn install
          service {{ secrets.SERVICE_NAME }} restart 
